version: "{build}"
branches:
  only:
    - master

image:
  - Visual Studio 2017

configuration:
  - Release

clone_folder: C:\projects\TrafficSim
install:
  - cmd: git submodule update --init --recursive

before_build:
  - cmd: |-
      cmake --version
      cd C:\projects\TrafficSim
      mkdir build
      cd build
      cmake -G "Visual Studio 15 2017 Win64" ..
build:
  project: C:\projects\TrafficSim\build\TrafficSim.sln
  verbosity: minimal
  parallel: true